## Constraint file constraint.xdc for BASYS3 FPGA board.
## Auto-generated by Constraint Generator on 25/11/2561 20:17:41

## Clock
set_property PACKAGE_PIN W5 [get_ports clock]
	set_property IOSTANDARD LVCMOS33 [get_ports clock]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clock]


## Switches
set_property PACKAGE_PIN V17 [get_ports {zoneSw[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[0]}]
set_property PACKAGE_PIN V16 [get_ports {zoneSw[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[1]}]
set_property PACKAGE_PIN W16 [get_ports {zoneSw[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[2]}]
set_property PACKAGE_PIN W17 [get_ports {zoneSw[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[3]}]
set_property PACKAGE_PIN W15 [get_ports {zoneSw[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[4]}]
set_property PACKAGE_PIN V15 [get_ports {zoneSw[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[5]}]
set_property PACKAGE_PIN W14 [get_ports {zoneSw[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[6]}]
set_property PACKAGE_PIN W13 [get_ports {zoneSw[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[7]}]
set_property PACKAGE_PIN V2 [get_ports {zoneSw[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[8]}]
set_property PACKAGE_PIN T3 [get_ports {zoneSw[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[9]}]
set_property PACKAGE_PIN T2 [get_ports {zoneSw[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[10]}]
set_property PACKAGE_PIN R3 [get_ports {zoneSw[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[11]}]
set_property PACKAGE_PIN W2 [get_ports {zoneSw[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[12]}]
set_property PACKAGE_PIN U1 [get_ports {zoneSw[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[13]}]
set_property PACKAGE_PIN T1 [get_ports {zoneSw[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[14]}]
set_property PACKAGE_PIN R2 [get_ports {zoneSw[15]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {zoneSw[15]}]


## LEDs
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property PACKAGE_PIN E19 [get_ports {led[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property PACKAGE_PIN U19 [get_ports {led[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property PACKAGE_PIN V19 [get_ports {led[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property PACKAGE_PIN W18 [get_ports {led[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property PACKAGE_PIN U15 [get_ports {led[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property PACKAGE_PIN U14 [get_ports {led[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property PACKAGE_PIN V14 [get_ports {led[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
set_property PACKAGE_PIN V13 [get_ports {led[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[8]}]
set_property PACKAGE_PIN V3 [get_ports {led[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[9]}]
set_property PACKAGE_PIN W3 [get_ports {led[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[10]}]
set_property PACKAGE_PIN U3 [get_ports {led[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[11]}]
set_property PACKAGE_PIN P3 [get_ports {led[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[12]}]
set_property PACKAGE_PIN N3 [get_ports {led[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[13]}]
set_property PACKAGE_PIN P1 [get_ports {led[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[14]}]
set_property PACKAGE_PIN L1 [get_ports {led[15]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {led[15]}]


## Seven segment


## Buttons
set_property PACKAGE_PIN U18 [get_ports menuBtn]
	set_property IOSTANDARD LVCMOS33 [get_ports menuBtn]
set_property PACKAGE_PIN T18 [get_ports snzBtn]
	set_property IOSTANDARD LVCMOS33 [get_ports snzBtn]
set_property PACKAGE_PIN W19 [get_ports minBtn]
	set_property IOSTANDARD LVCMOS33 [get_ports minBtn]
set_property PACKAGE_PIN T17 [get_ports plusBtn]
	set_property IOSTANDARD LVCMOS33 [get_ports plusBtn]
set_property PACKAGE_PIN U17 [get_ports offBtn]
	set_property IOSTANDARD LVCMOS33 [get_ports offBtn]


## PMOD A


## PMOD B
set_property PACKAGE_PIN A14 [get_ports {data[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property PACKAGE_PIN A16 [get_ports {data[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property PACKAGE_PIN B15 [get_ports {data[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property PACKAGE_PIN B16 [get_ports {data[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property PACKAGE_PIN A15 [get_ports {data[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
set_property PACKAGE_PIN A17 [get_ports {data[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
set_property PACKAGE_PIN C15 [get_ports {data[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
set_property PACKAGE_PIN C16 [get_ports {data[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]


## PMOD C
set_property PACKAGE_PIN K17 [get_ports enable]
	set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property PACKAGE_PIN M18 [get_ports select]
	set_property IOSTANDARD LVCMOS33 [get_ports select]
set_property PACKAGE_PIN N17 [get_ports rec]
	set_property IOSTANDARD LVCMOS33 [get_ports rec]
set_property PACKAGE_PIN P18 [get_ports play]
	set_property IOSTANDARD LVCMOS33 [get_ports play]
set_property PACKAGE_PIN L17 [get_ports light]
	set_property IOSTANDARD LVCMOS33 [get_ports light]
set_property PACKAGE_PIN M19 [get_ports backlight]
	set_property IOSTANDARD LVCMOS33 [get_ports backlight]


## PMOD X


## VGA


## USB RS-232


## USB PS/2 (HID)


## Quad SPI


## End file
