## Constraint file test.xdc for BASYS3 FPGA board.
## Auto-generated by Constraint Generator on 15/11/2561 17:29:24

## Clock
set_property PACKAGE_PIN W5 [get_ports clock]
	set_property IOSTANDARD LVCMOS33 [get_ports clock]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clock]


## Switches


## LEDs


## Seven segment


## Buttons


## PMOD A


## PMOD B
set_property PACKAGE_PIN A14 [get_ports {data[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property PACKAGE_PIN A16 [get_ports {data[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property PACKAGE_PIN B15 [get_ports {data[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property PACKAGE_PIN B16 [get_ports {data[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property PACKAGE_PIN A15 [get_ports {data[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[4]}]
set_property PACKAGE_PIN A17 [get_ports {data[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[5]}]
set_property PACKAGE_PIN C15 [get_ports {data[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[6]}]
set_property PACKAGE_PIN C16 [get_ports {data[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {data[7]}]


## PMOD C
set_property PACKAGE_PIN K17 [get_ports enable]
	set_property IOSTANDARD LVCMOS33 [get_ports enable]
set_property PACKAGE_PIN M18 [get_ports select]
	set_property IOSTANDARD LVCMOS33 [get_ports select]


## PMOD X


## VGA


## USB RS-232


## USB PS/2 (HID)


## Quad SPI


## End file
